html-modal-explore
ASKurochkin/simply-chocolate pull request #3
Opened 2023-03-24 17:35 UTC by KramchaninAlena

modal-explore

2023-03-24 17:49 UTC, ASKurochkin commented on src/partials/modal-explore.html
> +        ../images/broken-chokolat-sm@2x.png 2x
Картинка експортована у png - треба jpg

2023-03-24 17:56 UTC, ASKurochkin commented on src/partials/modal-explore.html
> +  <h2>Explore our <span class="title-brand">new chocolate</span>first!</h2>
Це робиться не так. Треба додати клас .section-title до h2, а клас .title-brand до спану. Ось так:
<h2 class="section-title">Explore our <span class="title-brand">new chocolate</span>first!</h2>

2023-03-24 17:56 UTC, ASKurochkin commented on src/partials/modal-explore.html
> +  <svg style="stroke: black">
Додавайте колір через css. Прописувати колір inline будемо, тільки у крайньому випадку, якщо інакше не працює.  style="stroke: black" - видалити.

2023-03-24 17:59 UTC, ASKurochkin commented on src/partials/modal-explore.html
> +      <input type="email" name="useremail" placeholder="Email" required />
placeholder треба писати, як на макеті - Enter your email, а не просто Email

2023-03-24 18:00 UTC, ASKurochkin commented on src/partials/modal-explore.html
> +    <label></label>
У цієї форми не буде лейблу - видаліть його. Достатньо плейсхолдеру.

2023-03-24 18:02 UTC, ASKurochkin requested changes
Подивіться мої коментарі. Також звертаю увагу, що картинки не додані до пушу. Тобто я бачу їх прописаними в в коді, але самих картинок немає.

2023-03-24 18:07 UTC, KramchaninAlena commented on src/partials/modal-explore.html
> +  <svg style="stroke: black">
Я так і буду робити, домовлялися ж поки без css. Я це зробила, щоб мені було її видно

2023-03-24 18:11 UTC, KramchaninAlena commented on src/partials/modal-explore.html
> +    <label></label>
Виправила. З картинками вирішую питання

2023-03-24 18:11 UTC, KramchaninAlena commented on src/partials/modal-explore.html
> +      <input type="email" name="useremail" placeholder="Email" required />
Виправила

2023-03-24 18:14 UTC, KramchaninAlena commented on src/partials/modal-explore.html
> +  <h2>Explore our <span class="title-brand">new chocolate</span>first!</h2>
Виправила

2023-03-24 18:19 UTC, KramchaninAlena commented on src/partials/modal-explore.html
> +        ../images/broken-chokolat-sm@2x.png 2x
є

2023-03-25 08:49 UTC, ASKurochkin commented
Я ще трохи допрацював від себе, наприклад, замінив в кінці span на div, бо при адаптаії видно, що то флекс-контейнер. Приймаємо.

2023-03-25 08:49 UTC, ASKurochkin approved these changes

2023-03-25 08:51 UTC, merged